// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma-admin-database/schema.prisma", 
  migrations: {
    path: "prisma-admin-database/migrations", 
  },
  datasource: {
    url: process.env["ADMIN_DATABASE_URL"],
  },
});
